### ISSUE TITLE
Add a way to provide env variables 

### ISSUE THREAD

**Issue by DRFR0ST** [DRFR0ST/react-instant#9]
**Is your feature request related to a problem? Please describe.**
I've stumbled upon a project that I couldn't get to run without manually adding a .env file.

**Describe the solution you'd like**
Providing a path with env vars would be useful. 

#### Path (prefered)
eg.
`react-instant DRFR0ST/circles-web --env ./myenvfile`

This command should copy the "myenvfile" file and paste it into the cloned project.

**Comment by xomod** [comment]
I'm taking this issue!
